import sharp from "sharp";
import { glob } from "glob";
import fsPromise from "node:fs/promises";
import fs from "node:fs";
import { execSync } from "node:child_process";

const sizes = [
  { width: 160, height: 160 },
  { width: 320, height: 320 },
];

// librsvg (used by sharp) cannot render WebP inside <image> — convert embeds to PNG.
const WEBP_DATA_URI_RE =
  /((?:xlink:)?href=["'])data:image\/webp;base64,([A-Za-z0-9+/=]+)(["'])/g;

async function replaceWebpEmbedsWithPng(svg: string): Promise<{
  svg: string;
  replaced: number;
}> {
  const matches: RegExpExecArray[] = [];
  let match: RegExpExecArray | null;

  WEBP_DATA_URI_RE.lastIndex = 0;
  while ((match = WEBP_DATA_URI_RE.exec(svg)) !== null) {
    matches.push(match);
  }

  if (matches.length === 0) {
    return { svg, replaced: 0 };
  }

  let result = svg;
  for (const match of matches) {
    const [full, prefix, base64, suffix] = match;
    const pngBuf = await sharp(Buffer.from(base64, "base64")).png().toBuffer();
    const replacement = `${prefix}data:image/png;base64,${pngBuf.toString(
      "base64"
    )}${suffix}`;
    result = result.replace(full, replacement);
  }

  return { svg: result, replaced: matches.length };
}

async function prepareSvgInput(file: string): Promise<Buffer | null> {
  const original = await fsPromise.readFile(file, "utf8");

  if (!original.trim()) {
    console.error(`Skipping empty SVG: ${file}`);
    return null;
  }

  const { svg, replaced } = await replaceWebpEmbedsWithPng(original);

  if (replaced > 0) {
    console.warn(
      `Replaced ${replaced} WebP embed(s) with PNG in ${file} (librsvg cannot render WebP in SVG <image>)`
    );
    await fsPromise.writeFile(file, svg);
  }

  return Buffer.from(svg);
}

async function deletePNGFiles() {
  const files = await glob("**/*_*x*.png"); // This pattern matches PNGs that were likely generated by the conversion function

  await Promise.all(
    files.map(async (file) => {
      await fsPromise.unlink(file);
      console.log("Deleted:", file);
    })
  );
}

async function convertSVGToPNGForFile(file: string) {
  const pendingSizes = sizes.filter((size) => {
    const outputPath = file.replace(
      ".svg",
      `_${size.width}x${size.height}.png`
    );

    if (fs.existsSync(outputPath)) {
      console.log("Skipped conversion for existing file:", outputPath);
      return false;
    }

    return true;
  });

  if (pendingSizes.length === 0) {
    return [];
  }

  const svgInput = await prepareSvgInput(file);
  if (!svgInput) {
    return [];
  }

  return (
    await Promise.all(
      pendingSizes.map(async (size) => {
        const outputPath = file.replace(
          ".svg",
          `_${size.width}x${size.height}.png`
        );

        try {
          // Copy the buffer per size — sharp can consume/reuse input buffers.
          await sharp(Buffer.from(svgInput))
            .resize({ width: size.width, height: size.height, fit: "inside" })
            .toFile(outputPath);

          console.log("Converted:", file, "to", outputPath);

          return outputPath;
        } catch (error) {
          console.error("Error converting:", file, error);

          throw error;
        }
      })
    )
  ).filter((val): val is string => !!val);
}

async function convertSVGToPNG() {
  const files = await glob("**/*.svg");

  const res = (await Promise.all(files.map(convertSVGToPNGForFile))).flat();

  if (res.length > 0) {
    execSync(`git add ${res.join(" ")}`);
  }
}

if (process.argv[2] === "delete") {
  deletePNGFiles();
} else if (process.argv[2] === "convert") {
  convertSVGToPNG();
} else {
  console.log("Please provide a valid command: delete or convert");
}
